#!/usr/bin/env perl 
#===============================================================================
#
#         FILE: check_default_gateway.pl
#
#        USAGE: ./check_default_gateway.pl
#
#  DESCRIPTION:
#
#      OPTIONS: ---
# REQUIREMENTS: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: James Zhu (), zhujian0805@gmail.com
# ORGANIZATION: ZJ
#      VERSION: 1.0
#      CREATED: 2015年10月02日 19时54分58秒
#     REVISION: ---
#===============================================================================

use strict;
use warnings;
use utf8;

my $IFCONFIG = '/sbin/ifconfig';
my @ifconfig = `$IFCONFIG`;
my %interfaces;

foreach (@ifconfig) {
    my $interface;
    if ( /(.*)\s+Link encap.*HWaddr/ .. /^$/ ) {
        if ( /(.*)\s+Link encap.*HWaddr (d8:d3:85:77:b9:50)/) {
            $interface = $1;
            $interfaces{$interface}{HWaddr} = $2;
            print $interface;
        }
        elsif (/inet addr:(\d{1,}.\d{1,}.\d{1,}.\d{1,})  Bcast:(\d{1,}.\d{1,}.\d{1,}.\d{1,})  Mask:(\d{1,}.\d{1,}.\d{1,}.\d{1,})/)
        {
            print $interface;
            $interfaces{$interface}{ipaddr} = $1;
            $interfaces{$interface}{bcase}  = $2;
            $interfaces{$interface}{mask}   = $3;
        }
    }
}
